### ISSUE TITLE
Plugin is only released to JCenter, which is going away

### ISSUE THREAD

**Issue by simonbasle** [reyerizo/jcstress-gradle-plugin#37]
JCenter is going read-only tomorrow.
It is going to be deleted altogether February 1st, 2022.
See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

@jerzykrlk are you planning to release on Maven Central going forward?

**Comment by jerzykrlk** [comment]
Hello Simon,

I was waiting until some alternative for Bintray appears and makes things easier. Now I think that I'll just move to Maven Central. 

Before that, I will change the group name to `com.github.reyerizo.gradle`, because `erizo` is already taken on GitHub. That's a Maven Central restriction.

Also, the Gradle plugin location will move accordingly. 

I can't promise - but I hope to fix all above within a month - and then relase a new version.

**Comment by jerzykrlk** [comment]
Yup, I've just received a notice from Bintray - I'll start moving away soon (within weeks).

**Comment by jerzykrlk** [comment]
Ok, I'm on my way:
- Sonatype ticket: https://issues.sonatype.org/browse/OSSRH-67990
- GitHub repo moved to 'reyerizo'.

**Comment by jerzykrlk** [comment]
Okay, published to Maven Central and to a new plugin location in Gradle Plugins:

`io.github.reyerizo.gradle.jcstress`.

Current version is 0.8.10 and may take a day or two to be approved by Gradle team (now it's Pending Approval).

**Comment by jerzykrlk** [comment]
The release process is not complete - it's now semi-manual, so for now I'll leave this ticket open.

**Comment by jerzykrlk** [comment]
Hello Simon, 

The Gradle plugin has been approved and can now be safely used.

**Comment by simonbasle** [comment]
@jerzykrlk I would suggest making that very prominent in the release https://github.com/reyerizo/jcstress-gradle-plugin/releases/tag/0.8.10 (ie part of the release title)

**Comment by jerzykrlk** [comment]
Hello Simon - thanks for the suggestion. I've updated the description.
